### DISCUSSION TITLE
Підтримка проксі

### DISCUSSION THREAD

**Discussion by OleksandrBlack** [arriven/db1000n#466] [Ideas]
https://github.com/Arriven/db1000n/issues/389

Завжди актуальний список проксі який використовується для спільної мети.
https://github.com/porthole-ascend-cinnamon/mhddos_proxy/blob/820defda23342fdaf90f2149d94b3464099d155b/runner.py#L15

Розробник
https://github.com/porthole-ascend-cinnamon

**Comment by Starodubysko** [comment]
За власним спостереженням додам, що переважна частина спільнот перейшла на цю програму саме завдяки відсутності мороки з VPN.
Звісно, ті хто тямить прикрутять OpenVPN чи ротацію проксі прямо в Docker і т.п., але, гадаю, для більшості це буде складно, навіть з гуглом під рукою.
А ще якщо враховувати, що машин десятки, то взагалі завал все налаштовувати

**Comment by arriven** [comment]
For anyone who want's to use this proxylist you can use following commandline flag:
`--proxy '{{ join (split (get_url "https://raw.githubusercontent.com/porthole-ascend-cinnamon/proxy_scraper/main/proxies.txt") "\n") "," }}'`

**Comment by arriven** [comment]
You can also pass that argument via `SYSTEM_PROXY` environment variable, i.e. `SYSTEM_PROXY='{{ join (split (get_url "https://raw.githubusercontent.com/porthole-ascend-cinnamon/proxy_scraper/main/proxies.txt") "\n") "," }}' go run main.go`

**Comment by arriven** [comment]
Please note that it only works starting from v0.8.12 release as `split <string> "\n"` was a bit broken before that

**Comment by OleksandrBlack** [comment]
https://github.com/Arriven/db1000n/commit/dbd53bfbb9e02357fcb8598e718366f663dc9e46

--proxy '{{ join (split (get_url "https://raw.githubusercontent.com/porthole-ascend-cinnamon/proxy_scraper/main/proxies.txt") "\n") "," }}'

SYSTEM_PROXY='{{ join (split (get_url "https://raw.githubusercontent.com/porthole-ascend-cinnamon/proxy_scraper/main/proxies.txt") "\n") "," }}' go run main.go

**Comment by OleksandrBlack** [comment]
[Arriven](https://github.com/Arriven)
Doesn't work for Windows
![error](https://user-images.githubusercontent.com/13917465/160397035-de5617cb-7d83-44f8-8b23-747e51c5fcdd.jpg)

**Comment by arriven** [comment]
hmm, might be something to do with how powershell/cmd handle string arguments. Can you check if that approach works for you if you put everything into a docker-compose file like this?

```yaml
version: "3.9"

services:
  programm:
    image: ghcr.io/arriven/db1000n
    restart: unless-stopped
    environment:
      SYSTEM_PROXY: '{{ join (split (get_url "https://raw.githubusercontent.com/porthole-ascend-cinnamon/proxy_scraper/main/proxies.txt") "\n") "," }}'
      DEBUG: "true"
```
