### ISSUE TITLE
dcoker-compose example doesn't work

### ISSUE THREAD

**Issue by industral** [Arriven/db1000n#216]
Using slightly modified docker-compose example from https://github.com/Arriven/db1000n/blob/main/docker-compose.yml

```yaml
version: "3.3"

services:
  # creates OpenVPN Docker container to first provider that randomly picks .conf file
  ovpn_01:
    image: ghcr.io/wfg/openvpn-client:2.1.0
    cap_add:
      - NET_ADMIN
    security_opt:
      - label:disable
    restart: unless-stopped
    volumes:
      - /dev/net:/dev/net:z
      - /root/ovpn_udp/:/data/vpn:z
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    environment:
      KILL_SWITCH: "on"
      HTTP_PROXY: "off"
      VPN_AUTH_SECRET: provider01_secret
      VPN_CONFIG_PATTERN: "*.ovpn" # this will match provider01_country01.conf, provider01_country02.conf etc
    secrets:
      - provider01_secret

  # creates OpenVPN Docker container to first provider with specific .conf file
  ovpn_02:
    image: ghcr.io/wfg/openvpn-client:2.1.0
    cap_add:
      - NET_ADMIN
    security_opt:
      - label:disable
    restart: unless-stopped
    volumes:
      - /dev/net:/dev/net:z
      - /root/ovpn_udp/:/data/vpn:z
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    environment:
      KILL_SWITCH: "on"
      HTTP_PROXY: "off"
      VPN_AUTH_SECRET: provider01_secret
      VPN_CONFIG_FILE: "*.ovpn"
    secrets:
      - provider01_secret

  # creates OpenVPN Docker container to second provider with specific .conf file
  ovpn_03:
    image: ghcr.io/wfg/openvpn-client:2.1.0
    cap_add:
      - NET_ADMIN
    security_opt:
      - label:disable
    restart: unless-stopped
    volumes:
      - /dev/net:/dev/net:z
      - /root/ovpn_udp/:/data/vpn:z
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    environment:
      KILL_SWITCH: "on"
      HTTP_PROXY: "off"
      VPN_AUTH_SECRET: provider01_secret
      VPN_CONFIG_FILE: "*.ovpn"
    secrets:
      - provider01_secret

  # this Docker container will use VPN 01
  db1000n_01:
    image: ghcr.io/arriven/db1000n-advanced
    restart: unless-stopped
    depends_on:
      - ovpn_01
    network_mode: "service:ovpn_01"

  # this Docker container will use VPN 02
  db1000n_02:
    image: ghcr.io/arriven/db1000n-advanced
    restart: unless-stopped
    depends_on:
      - ovpn_02
    network_mode: "service:ovpn_02"

  # this Docker container will use VPN 03
  db1000n_03:
    image: ghcr.io/arriven/db1000n-advanced
    restart: unless-stopped
    depends_on:
      - ovpn_03
    network_mode: "service:ovpn_03"

secrets:
  provider01_secret:
    file: /root/nordvpn-creds.txt
```

```bash
# docker ps
CONTAINER ID   IMAGE                              COMMAND                  CREATED         STATUS                          PORTS     NAMES
2b81f0531ee8   ghcr.io/arriven/db1000n-advanced   "./main -c https://r…"   6 minutes ago   Up 6 minutes                              root_db1000n_01_1
dcd2a0472edf   ghcr.io/wfg/openvpn-client:2.1.0   "/data/scripts/entry…"   6 minutes ago   Restarting (1) 37 seconds ago             root_ovpn_03_1
fe1c70543ee0   ghcr.io/wfg/openvpn-client:2.1.0   "/data/scripts/entry…"   6 minutes ago   Restarting (1) 38 seconds ago             root_ovpn_02_1
052add96c798   ghcr.io/wfg/openvpn-client:2.1.0   "/data/scripts/entry…"   6 minutes ago   Up 6 minutes (healthy)                    root_ovpn_01_1
```

As you can see 1 container db_1000n + ovpn works fine, but the rest can't spin up.

```bash
# docker logs -n 50 root_ovpn_02_1
Allowing established and related connections...
Allowing loopback connections...
Allowing Docker network connections...
Allowing specified subnets...
Allowing remote servers in configuration file...
  Using:
dig: '' is not a legal name (unexpected end of input)
Allowing connections over VPN interface...
Preventing anything else...
iptables rules created and routes configured.

Configuring OpenVPN authentication.
Running OpenVPN client.

2022-03-07 17:02:55 Cipher negotiation is disabled since neither P2MP client nor server mode is enabled
Options error: You must define TUN/TAP device (--dev)
Use --help for more information.

---- Running with the following variables ----
Kill switch: on
HTTP proxy: off
SOCKS proxy: off
Proxy username secret: none
Proxy password secret: none
Allowing subnets: none
Using OpenVPN log level: 3
Listening on: none
Using configuration file: /data/vpn/*.ovpn
Creating /data/vpn/*.ovpn.modified and making required changes to that file.
grep: /data/vpn/*.ovpn: No such file or directory
Changes made.

Creating VPN kill switch and local routes.
Allowing established and related connections...
Allowing loopback connections...
Allowing Docker network connections...
Allowing specified subnets...
Allowing remote servers in configuration file...
  Using:
dig: '' is not a legal name (unexpected end of input)
Allowing connections over VPN interface...
Preventing anything else...
iptables rules created and routes configured.

Configuring OpenVPN authentication.
Running OpenVPN client.

2022-03-07 17:03:58 Cipher negotiation is disabled since neither P2MP client nor server mode is enabled
Options error: You must define TUN/TAP device (--dev)
Use --help for more information.
```

From error log you can see something wrong with `/data/vpn/` folder. For some reason it can't find any file...
I can't connect to that docker due to

```
# docker exec -it root_ovpn_02_1 sh
Error response from daemon: Container fe1c70543ee0dbcfdfd96a1b26cd8312c33e459935f38e09439f7385e8a4cf3b is restarting, wait until the container is running
```

Not sure how to spin it up.

```bash
# uname -a
Linux XX-XXXX-XXXXX 4.15.0-169-generic #177-Ubuntu SMP Thu Feb 3 10:50:38 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
# docker -v
Docker version 20.10.12, build e91ed57
# docker-compose -v
docker-compose version 1.17.1, build unknown
```
