### ISSUE TITLE
Updater dont work in docker-compose

### ISSUE THREAD

**Issue by Pandanom** [Arriven/db1000n#439]
## Expected Behavior
db1000n in updater mode, should fetch configuration bypassing VPN and store it in shared volume

## Actual Behavior

Creating network "db1000nexpvpn_default" with the default driver
Creating db1000nexpvpn_updater_1 ... error
Creating autoheal                ... done
Creating expressvpn              ... done

ERROR: for db1000nexpvpn_updater_1  Cannot start service updater: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "./db1000n": stat ./db1000n: no such file or directory: unknown

ERROR: for updater  Cannot start service updater: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "./db1000n": stat ./db1000n: no such file or directory: unknown

## Steps to Reproduce the Problem
I used simular setup to one in the docks (https://arriven.github.io/db1000n/advanced-docs/docker-vpn/#setting-up-vpn-for-docker-users), but slightly changed for expressvpn 

  1. Create docker-compose.yml
  2. docker-compose pull
  3. docker-compose up -d

## Specifications
In older version everything was fine, I got this error after pull
  - Version: v0.8.9

**Comment by Arriven** [comment]
@bitshape AFAIR you've been doing this docker compose? Can you take a look while I'm in a bunker?

**Comment by Arriven** [comment]
Ah wait, I think I know what could be the cause, can you try changing compose to use entrypoint instead of command or vice versa? (excluding exe name and leaving just arguments)
Or alternatively there should be an environment variable that you can use that would be even better

**Comment by Arriven** [comment]
https://github.com/Arriven/db1000n/blob/main/src/runner/config/updater.go#L15
This one, it's more common to configure containers via environment variables rather then commandline flags and most other guides already use that

**Comment by Pandanom** [comment]
Like this?
It starts as regular db1000n
`    updater:
        image: ghcr.io/arriven/db1000n:latest
        restart: unless-stopped
        labels:
          autoheal: "true"
        #entrypoint: "./db1000n --updater-mode"
        command: bash -c "./db1000n --updater-mode"
        volumes:
          - ./config:/usr/src/app/config:z
        environment:
          UPDATER_DESTINATION_CONFIG: "config/config.json"
        healthcheck:
          test: [ "CMD", "test", "-f", "config/config.json" ]
          timeout: 5s
          interval: 5s
          retries: 5`

**Comment by Arriven** [comment]
@Pandanom something like this

```
# [OPTIONAL]
  # run db1000n in updater mode, which will fetch configuration bypassing VPN and store it in shared volume
  updater:
    image: ghcr.io/arriven/db1000n
    restart: unless-stopped
    labels:
      autoheal: "true"
    volumes:
      - ./config:/usr/src/app/config:z
    environment:
      UPDATER_DESTINATION_CONFIG: "config/config.json"
      UPDATER_MODE: true
    healthcheck:
      test: ["CMD", "test", "-f", "config/config.json"]
      timeout: 5s
      interval: 5s
      retries: 5
```

**Comment by Arriven** [comment]
I have a feeling that healthcheck could be broken also since I've switched to a distroless image

**Comment by bitshape** [comment]
@Arriven I’m taking a look

**Comment by bitshape** [comment]
@Arriven check linked PR. I don't think it's `ko` issue, it's just that `--updater-mode` exists when it should not.

**Comment by bitshape** [comment]
@Pandanom in addition to the fix proposed above, I think your config also needs some changes:

```yaml
updater:
  image: ghcr.io/arriven/db1000n:latest
  restart: unless-stopped
  labels:
    autoheal: "true"
  environment:
    UPDATER_MODE: "true"
  volumes:
    - ./config:/usr/src/app/config:z
  healthcheck:
    test: [ "CMD", "test", "-f", "config/config.json" ]
    timeout: 5s
    interval: 5s
    retries: 5

db1000n_01:
  image: ghcr.io/arriven/db1000n:latest
  restart: unless-stopped
  depends_on:
    updater:
      condition: service_healthy
  labels:
    autoheal: "true"
  environment:
    CONFIG: "config/config.json"
  volumes:
    - ./config:/usr/src/app/config:z
  healthcheck:
    test: [ "CMD", "nslookup", "google.com", "8.8.8.8" ]
    timeout: 10s
    interval: 30s
    retries: 3
```

The important parts:

- both updater and regular db1000n container need to point to the same volume
- normal db1000n container needs `CONFIG: "config/config.json"`, otherwise it will load config from Github

**Comment by PerchunPak** [comment]
@bitshape seems like you looking to old config, here all real changes that you made (comparing with upstream):
![Untitled](https://user-images.githubusercontent.com/68118654/160256664-26afb7dc-7273-4f70-a360-924730b8cdc7.png)
Also you moved some sections and add tag `latest` to images.

**Comment by bitshape** [comment]
@PerchunPak 👍 none of those parts are required and really depend on your particular setup so I omitted them from my suggestion on purpose.

**Comment by bitshape** [comment]
@Arriven you might be right about `ko` but it doesn't seem to be related to the healthcheck.

v0.8.3 (pre ko build) Docker container runs fine
v0.8.4 (ko introduced) this version isn't published
v0.8.5 (built with ko) fails with the following config:

```yaml
updater:
  image: ghcr.io/arriven/db1000n:v0.8.5
  restart: unless-stopped
  labels:
    autoheal: "true"
  environment:
    UPDATER_MODE: "true"
  volumes:
    - ./config:/usr/src/app/config:z
```

Error:

```
21:03:06.165067 main.go:51: DB1000n [Version: v0.8.5][PID=1]
21:03:06.201548 config.go:63: Loading config from "https://raw.githubusercontent.com/db1000n-coordinators/LoadTestConfig/main/config.v0.7.json"
21:03:06.201604 updater.go:30: Error writing config: open config/config.json: no such file or directory
db1000n-updater_1 exited with code 0
```
