### ISSUE TITLE
Service "updater" is missing a healthcheck configuration

### ISSUE THREAD

**Issue by industral** [Arriven/db1000n#444]
running docker-compose get the following issue

```
ERROR: for db1000n_38  Service "updater" is missing a healthcheck configuration

ERROR: for db1000n_31  Service "updater" is missing a healthcheck configuration

ERROR: for db1000n_03  Service "updater" is missing a healthcheck configuration

....
```

**Comment by Arriven** [comment]
@bitshape seems like "service_started" condition also requires a healthcheck to be defined. I suggest we just enable pprof endpoint on it and use that endpoint/port availability as a healthcheck? Not sure how that works with docker compose though as I only did that with k8s

**Comment by bitshape** [comment]
@Arriven @industral No, it definitely doesn't need health check to be define for `service_started`: https://docs.docker.com/compose/compose-file/compose-file-v2/#depends_on

> In the above example, Compose waits for the redis service to be started (legacy behavior)

My personal config below works with v0.8.10:

```yaml
updater:
  image: ghcr.io/arriven/db1000n:v0.8.10
  restart: unless-stopped
  labels:
    autoheal: "true"
  environment:
    UPDATER_MODE: "true"
    UPDATER_DESTINATION_CONFIG: "/ko-app/config/config.json"
  volumes:
    - ./config:/ko-app/config:z

db1000n_01:
  image: ghcr.io/arriven/db1000n:v0.8.10
  restart: unless-stopped
  depends_on:
    updater:
      condition: service_started
    ovpn_01:
      condition: service_healthy
  network_mode: "service:ovpn_01"
  labels:
    autoheal: "true"
  environment:
    STRICT_COUNTRY_CHECK: "true"
    CONFIG: "/ko-app/config/config.json"
  volumes:
    - ./config:/ko-app/config:z
```

pprof is an interesting workaround but I think more reliable solution would be implementing ping/nslookup non-blocking go routine that will be used if a new option `--enable-healthcheck` is passed to container, so the process simply exits and gets restarted by Docker if it can't access Internet.
